server:
  port: 8702     #指定服务端口
eureka:
  instance:
    hostname: nodeB
  client:
    service-url:
#      defaultZone: http://localhost:8701/eureka/,http://localhost:8703/eureka/
# 使用容器技术部署
      defaultZone: http://${node_ip_1}/eureka/,http://${node_ip_3}/eureka/