server:
  port: 8701     #指定服务端口
eureka:
  instance:
    hostname: nodeA
  client:
    service-url:
#      defaultZone: http://localhost:8702/eureka/,http://localhost:8703/eureka/
# 使用容器技术部署
      defaultZone: http://${node_ip_2}:8701/eureka/,http://${node_ip_3}:8701/eureka/