server:
  port: 8703     #指定服务端口
eureka:
  instance:
    hostname: nodeC
  client:
    service-url:
#      defaultZone: http://localhost:8701/eureka/,http://localhost:8702/eureka/
# 使用容器技术部署
      defaultZone: http://${node_ip_1}:8701/eureka/,http://${node_ip_2}:8701/eureka/