spring:
  application:
    name: ts.eureka.center
eureka:
  client:
    registerWithEureka: true  #是否将eureka自身作为应用注册到eureka注册中心
    fetchRegistry: true       #为true时，可以启动，但报异常：Cannot execute request on any known server