server:
  port: 8769    #指定服务端口
#  context-path: /eureka-ocr
spring:
  application:
    name: ts.eureka.config
  cloud:
    config:
      server:
        git:
          uri: http://192.168.99.100/root/ts-eureka-config.git # git地址 git@192.168.99.100:root/ts-eureka-config.git
          timeout: 30000
          username: root
          password: 12345678

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
