server:
  port: 8769    #指定服务端口
#  context-path: /eureka-ocr
spring:
  application:
    name: ts.eureka.config
  cloud:
    config:
      server:
        git:
          uri: http://192.168.99.100/root/ts-eureka-config.git # git地址 git@192.168.99.100:root/ts-eureka-config.git
          timeout: 30000
          username: root
          password: 12345678
    bus:
      trace: ## 开启消息跟踪
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
#    virtual-host: spring_cloud_virtual

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8701/eureka/,http://localhost:8702/eureka/,http://localhost:8703/eureka/
management:
  security: ## 刷新时，关闭安全验证
    enabled: false