server:
  port: 8751
spring:
  application:
    name: ts.eureka.turbine
turbine:
  appConfig:  ts.eureka.program,ts.eureka.client
#  app-config-list: ts.eureka.zuul,ts.eureka.config,ts.eureka.program
  aggregator:
    clusterConfig: MAIN
  clusterNameExpression: metadata['cluster']
eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8701/eureka/,http://localhost:8702/eureka/,http://localhost:8703/eureka/