server:
  port: 8766
spring:
  application:
    name: ts.eureka.turbine
turbine:
  appConfig:  ts.eureka.program,node02
  aggregator:
    clusterConfig: MAIN
  clusterNameExpression: metadata['cluster']
eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/