server:
  port: 8762    #指定服务端口
spring:
  application:
    name: ts.eureka.client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8701/eureka/,http://localhost:8702/eureka/,http://localhost:8703/eureka/
  instance:
    metadata-map:
      cluster:  MAIN