server:
  port: 8762     #指定服务端口
spring:
  application:
    name: ts-eureka-invoke
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/